### ISSUE TITLE
Issue with code logic for Week 2 exercise 

### ISSUE THREAD

**Issue by AlphaNumeric99** [pala9999/python#1]
In your file [loop_list.py](https://github.com/pala9999/python/blob/main/week2/loop_list.py#L97) 
Your logic is working for the list [4,5,6,2,9] but it fails for the list [4,5,2,6,9]. 

A better way to do this would be 
```
print("\n****  for loop replace the smallest value with the largest one *****")
listA = [4,5,2,6,9]
print("Before:",listA)
max_num=max(listA)
small_num_index = -1
for i in range (0,len(listA)) :
    if listA[i] == min(listA) :
            small_num_index = I
            break
listA[small_num_index] = max_num
print("After:",listA)
```

This will address the use case even if the values of the array/list change over time. Kindly try the same with the While loop.

**Comment by pala9999** [comment]
Thank you.
